steps:
    - name: 'gcr.io/cloud-builders/docker'
      dir:  'kubeflow'   # remove-for-manual
      args: [ 'build', '-t', 'gcr.io/ai-analytics-solutions/testing:latest', 'kubeflow' ]
images:
    - 'gcr.io/ai-analytics-solutions/testing:latest'
